# -*- coding: utf-8 -*-
"""INTERN_P1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAiiEfaQ5ossNLUQnKbRfztkgsKV2CHZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

x = pd.read_excel('/content/Dataset for Data Analytics.xlsx')

x.head()

x.notnull().sum()

x.replace('', np.nan, inplace=True)

x['CouponCode'] =x['CouponCode'].replace(['null', 'NULL', 'NaN', ''], np.nan)

x.head(12)

x.isnull().sum()

x.describe()

print(x.duplicated())

print(x.duplicated().sum())

text_cols = x.select_dtypes(include=['object']).columns
for col in text_cols:
    x['CouponCode'] = x['CouponCode'].fillna(x['CouponCode'].mode()[0])

text_cols

x.head(12)

x['Date'] = pd.to_datetime(x['Date'], errors='coerce')
print("Invalid Dates:")
print(x['Date'].isnull().sum())

print("Updated Data Types:")
print(x.dtypes)

for col in text_cols:
    x[col] = x[col].astype(str).str.strip()

print("Missing values after cleaning:")
print(x.isnull().sum())

print("Duplicate rows after cleaning:")
print(x.duplicated().sum())

x.to_csv('/content/cleaned_dataset.csv', index=False)
print("Cleaning complete")

